Repository falcosecurity/event-generator, pull requests merged in 2020-04, with the labels that each got.

#17 chore(events/k8saudit): pull in all k8s auth modes
  cmd/run.go
  go.mod
  go.sum
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none, size/S

#18 fix(Makefile): correct `make test` when no bundle
  Makefile
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS

#14 Add /var/lib/rpm
  Dockerfile
Labels: approved, area/pkg, dco-signoff: yes, kind/cleanup, lgtm, release-note-none, size/XS

#20 fix(Dockerfile): add bash required by helper.RunShell
  Dockerfile
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note, size/XS

#25 fix(events/k8saudit): correct misplaced reader when loading YAML
  events/k8saudit/yaml_loader.go
Labels: approved, area/events, dco-signoff: yes, kind/bug, lgtm, release-note, size/XS
