Repository falcosecurity/event-generator, pull requests merged in 2022-04, with the labels that each got.

#59 Release docker images for arm64
  .circleci/config.yml
  .goreleaser.yml
  Dockerfile
Labels: lgtm, approved, dco-signoff: yes, size/M, kind/feature

#60 update: set a 60m timeout for both circleCI and goreleaser.
  .circleci/config.yml
Labels: lgtm, approved, dco-signoff: yes, kind/cleanup, area/commands, size/XS

#62 update: since we are forcing docker version 20.x, buildx is already provided by it
  .circleci/config.yml
Labels: lgtm, approved, dco-signoff: yes, kind/cleanup, area/commands, size/S

#63 chore: restore old buildx install.
  .circleci/config.yml
Labels: lgtm, approved, dco-signoff: yes, kind/bug, area/commands, size/XS
