Repository falcosecurity/event-generator, pull requests merged in 2024-06, with the labels that each got.

#214 vote: docs(OWNERS): add alacuku (Aldo Lacuku) to approvers
  OWNERS
Labels: lgtm, approved, kind/documentation, dco-signoff: yes, size/XS

#211 Feature: Add support for testing falco rules using declarative YAML files in event-generator
  cmd/common.go
  cmd/declarative.go
  cmd/run.go
  cmd/test.go
  events/exampleyamlfile.yml
  pkg/declarative/helpers.go
  pkg/declarative/runner.go
  pkg/declarative/yamltypes.go
Labels: size/L, lgtm, approved, dco-signoff: yes, kind/feature

#157 Added an event for default rule "Sudo Potential Privilege Escalation"
  events/syscall/sudo_potential_privilege_escalaton.go
Labels: lgtm, approved, dco-signoff: yes, size/M, kind/feature, area/events, lifecycle/stale
