Repository falcosecurity/event-generator, pull requests merged in 2024-10, with the labels that each got.

#227 chore(dockerignore): use white-list approach
  .dockerignore
Labels: lgtm, approved, dco-signoff: yes, kind/cleanup, kind/feature, size/S

#228 build: fix cross-compilation
  Makefile
Labels: lgtm, approved, dco-signoff: yes, kind/bug, area/commands, size/XS

#233 update(ci): use arm64 CNCF runners for GH actions
  .github/workflows/ci.yaml
Labels: lgtm, approved, dco-signoff: yes, kind/cleanup, area/pkg, size/XS
